# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
- repo: https://github.com/psf/black-pre-commit-mirror
  rev: 23.9.1
  hooks:
  - id: black
    language_version: python3.11
- repo: https://github.com/adrybakov/pre-commit-hooks
  rev: 0.2.1                # Check available tags on the GitHub page
  hooks:
    - id: license-headers   # Required
      args:                 # Optional (as the next lines)
        - --license-file    # If license summary is not in a "LICENSE" file
        - L-HEADER          # Path to the license summary file
        - --update-year     # If you want to automatically update the year
        - --verbose         # (Added in 0.2.0) If you want each modified filename to be printed
