name: Feature request
description: Suggest an idea for this project
title: "[ENH]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: problem
    attributes:
      label: What are you missing?
      description: Describe the problem you have
      placeholder: A clear and concise description of what is missing.
    validations:
      required: true
  - type: textarea
    id: desired-solution
    attributes:
      label: What would you like to have?
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Do you want to add anything?
      description: Additional comments
      placeholder: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: OS
      description: What operating system are you using?
      options:
        - MacOS
        - Linux
        - Windows
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Magnopy version
      description: What version of our software are you running?
      placeholder: ex. 0.1.0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Use command
        ```bash
        magnopy
        or
        magnopy -v
        or
        magnopy --version
        ```
        in your terminal to check the version of Magnopy.
  - type: input
    id: commit
    attributes:
      label: Hash of the commit
      description: What commit is the base for the release?
      placeholder: ex. 060e69cd7e87c299c26f50f0a926667825681759
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Use command
        ```bash
        magnopy --git-commit
        or
        magnopy -gc
        ```
        in your terminal to check the hash of the commit.
