usage: magnopy [-h] [-v] [command ...]

                #   #
                #####
                # # #
                # # #
                #####
                 ###
                 ###   #   #  ###   ###  #   #  ###  ####  #   #
                 ####  ## ## #   # #     ##  # #   # #   # ## ##
                 ####  # # # ##### #  ## # # # #   # ####   ###
                 ####  #   # #   # #   # #  ## #   # #       #
                 ####  #   # #   #  ###  #   #  ###  #       #
                 #############################################
                 ##                                         ##
                 ##           Version: 0.6.0.dev            ##
                 ##         Release date: Undefined         ##
                 ##                                         ##
                 ##           License: GNU GPLv3            ##
                 ##       Documentation: magnopy.org        ##
                 ##     Copyright (C) 2023 Magnopy Team     ##
                 ##                                         ##
                 #############################################

Available scripts are:

* magnopy-optimize-sd

* magnopy-lswt

To call for help for each script type <script name> --help
Information below is relevant only to 'magnopy' command.

positional arguments:
  command        command/commands on what to do. Use to display information
                 about Magnopy. Choose from 'logo', 'warranty', 'test'

options:
  -h, --help     show this help message and exit
  -v, --version  print version of Magnopy
