usage: magnopy [-h] [-v] [command ...]

███╗   ███╗  █████╗   ██████╗  ███╗   ██╗  ██████╗  ██████╗  ██╗   ██╗
████╗ ████║ ██╔══██╗ ██╔════╝  ████╗  ██║ ██╔═══██╗ ██╔══██╗ ╚██╗ ██╔╝
██╔████╔██║ ███████║ ██║  ███╗ ██╔██╗ ██║ ██║   ██║ ██████╔╝  ╚████╔╝
██║╚██╔╝██║ ██╔══██║ ██║  ╚██║ ██║╚██╗██║ ██║   ██║ ██╔═══╝    ╚██╔╝
██║ ╚═╝ ██║ ██║  ██║ ╚██████╔╝ ██║ ╚████║ ╚██████╔╝ ██║         ██║
╚═╝     ╚═╝ ╚═╝  ╚═╝  ╚═════╝  ╚═╝  ╚═══╝  ╚═════╝  ╚═╝         ╚═╝
                                                           ▄   ▄
                    Version: 0.5.0.dev                     █▀█▀█
                Documentation: magnopy.org                 █▄█▄█
                 Release date: Undefined                    ███   ▄▄
                    License: GNU GPLv3                      ████ █  █
          Copyright (C) 2023-2026  Magnopy Team             ████    █
                                                            ▀▀▀▀▀▀▀▀

Available scripts are:

* magnopy-optimize-sd

* magnopy-lswt

To call for help for each script type <script name> --help
Information below is relevant only to 'magnopy' command.

positional arguments:
  command        command/commands on what to do. Use to display some
                 information about package. Choose from 'logo', 'warranty'

options:
  -h, --help     show this help message and exit
  -v, --version  print version of Magnopy
