usage: magnopy [-h] [-v] [{logo,warranty} ...]

███╗   ███╗  █████╗   ██████╗  ███╗   ██╗  ██████╗  ██████╗  ██╗   ██╗
████╗ ████║ ██╔══██╗ ██╔════╝  ████╗  ██║ ██╔═══██╗ ██╔══██╗ ╚██╗ ██╔╝
██╔████╔██║ ███████║ ██║  ███╗ ██╔██╗ ██║ ██║   ██║ ██████╔╝  ╚████╔╝
██║╚██╔╝██║ ██╔══██║ ██║  ╚██║ ██║╚██╗██║ ██║   ██║ ██╔═══╝    ╚██╔╝
██║ ╚═╝ ██║ ██║  ██║ ╚██████╔╝ ██║ ╚████║ ╚██████╔╝ ██║         ██║
╚═╝     ╚═╝ ╚═╝  ╚═╝  ╚═════╝  ╚═╝  ╚═══╝  ╚═════╝  ╚═╝         ╚═╝
                                                           ▄   ▄
                      Version: 0.4.0                       █▀█▀█
                Documentation: magnopy.org                 █▄█▄█
              Release date: 23 October 2025                 ███   ▄▄
                    License: GNU GPLv3                      ████ █  █
          Copyright (C) 2023-2025  Magnopy Team             ████    █
                                                            ▀▀▀▀▀▀▀▀

Available scripts are:

* magnopy-optimize-sd

* magnopy-lswt

To call for help for each script type <script name> --help
Information below is relevant only to 'magnopy' command.

positional arguments:
  {logo,warranty}  command/commands on what to do. Use to display some
                   information about package.

options:
  -h, --help       show this help message and exit
  -v, --version    print version of magnopy
